export const GET_TRACKERS_SUCCESS = "GET_TRACKERS_SUCCESS";
export const SAVE_TRACKER_SUCCESS = "SAVE_TRACKER_SUCCESS";

export const GET_MEAL_SUCCESS = "GET_MEAL_SUCCESS";
export const SAVE_MEAL_SUCCESS = "SAVE_MEAL_SUCCESS";